name: Development Workflow

on:
  push:
    branches: [master]
  pull_request:

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27

  test-deploy-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.14]
        os: [ubuntu-latest, macos-latest]
        include:
          - go: 1.13
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -i -ldflags "-s -w -X github.com/drakkan/sftpgo/version.commit=`git describe --always --dirty` -X github.com/drakkan/sftpgo/version.date=`date -u +%FT%TZ`" -o sftpgo

      - name: Initialize data provider
        run: ./sftpgo initprovider

      - name: Run tests using SQLite provider
        run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true

      - name: Prepare artifact
        run: |
          mkdir output
          cp sftpgo output/
          cp sftpgo.json output/
          cp -r templates output/
          cp -r static output/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sftpgo-${{ matrix.os }}-go${{ matrix.go }}
          path: output

      - name: Run tests using bolt provider
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.go == '1.14' }}
        run: |
          rm -f sftpgo.db
          export SFTPGO_DATA_PROVIDER__DRIVER=bolt
          go test -v ./config -covermode=atomic
          go test -v ./httpd -covermode=atomic
          go test -v ./sftpd -covermode=atomic

      - name: Run tests using memory provider
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.go == '1.14' }}
        run: |
          export SFTPGO_DATA_PROVIDER__DRIVER=memory
          export SFTPGO_DATA_PROVIDER__NAME=
          go test -v ./... -covermode=atomic

  test-deploy-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Build
        run: |
          $GIT_COMMIT = (git describe --always --dirty) | Out-String
          $DATE_TIME = ([datetime]::Now.ToUniversalTime().toString("yyyy-MM-ddTHH:mm:ssZ")) | Out-String
          go build -i -ldflags "-s -w -X github.com/drakkan/sftpgo/version.commit=$GIT_COMMIT -X github.com/drakkan/sftpgo/version.date=$DATE_TIME" -o sftpgo.exe

      - name: Initialize data provider
        run: .\sftpgo.exe initprovider

      - name: Run tests
        run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Prepare artifact
        run: |
          mkdir output
          xcopy.exe .\sftpgo.exe .\output
          xcopy.exe .\sftpgo.json .\output
          move .\templates .\output
          move .\static .\output

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sftpgo-windows
          path: output
